apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: workflow-events-listener
  namespace: argo-events
spec:
  eventBusName: default
  template:
    serviceAccountName: operate-workflow-sa
  resource:
    workflow-events-changes:
      group: argoproj.io
      version: v1alpha1
      resource: workflows
      operation: create
      eventTypes:
        - ADD
        - DELETE
        - UPDATE
      filter:
        afterStart: true
