apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minio
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      automountServiceAccountToken: false
      containers:
      - command:
        - minio
        - server
        - --console-address
        - :9001
        - /data
        env:
        - name: MINIO_ACCESS_KEY
          value: {{ .Values.secret.accesskey }}
        - name: MINIO_SECRET_KEY
          value: {{ .Values.secret.secretkey }}
        image: minio/minio:RELEASE.2022-11-17T23-20-09Z
        lifecycle:
          postStart:
            exec:
              command:
              - mkdir
              - -p
              - /data/my-bucket
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: {{ .Values.deployment.livenessProbePort }}
          initialDelaySeconds: {{ .Values.deployment.livenessProbeInitialDelaySeconds }}
          periodSeconds: {{ .Values.deployment.livenessProbePeriodSeconds }}
        name: main
        ports:
        - containerPort: {{ .Values.deployment.apiContainerPort }}
          name: api
        - containerPort: {{ .Values.deployment.dashboardContainerPort }}
          name: dashboard
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: {{ .Values.deployment.readinessProbePort }}
          initialDelaySeconds: {{ .Values.deployment.readinessProbeInitialDelaySeconds }}
          periodSeconds: {{ .Values.deployment.readinessProbePeriodSeconds }}