apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
  name: minio
spec:
  ports:
  - name: api
    port:  {{ .Values.service.apiPort }}
    protocol: TCP
    targetPort: {{ .Values.service.apiTargetPort }}
  - name: dashboard
    port: {{ .Values.service.dashboardPort }}
    protocol: TCP
    targetPort: {{ .Values.service.dashboardTargetPort }}
  selector:
    app: minio