minio:
  enabled: true

read:
  extraEnv:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
  extraArgs:
    - -memberlist.bind-addr=$(MY_POD_IP)

write:
  extraEnv:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
  extraArgs:
    - -memberlist.bind-addr=$(MY_POD_IP)
