# This workflow sets up Testkube Kubernetes Tests

name: Testkube Kubernetes Tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

permissions:
  contents: read

jobs:
  testkube:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: AbsaOSS/k3d-action@v2
        name: "Create K3d Cluster"
        with:
          cluster-name: "test-cluster-1"
          args: >-
            --agents 1
            --no-lb
            --image docker.io/rancher/k3s:v1.27.2-k3s1
            --k3s-arg "--no-deploy=traefik,servicelb,metrics-server@server:*"

      - name: Get Cluster Info
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          kubectl get nodes
          sudo kubeadm init
          echo "kubeconfig-file-location:" $KUBECONFIG
          echo "current-context:" $(kubectl config current-context)
          cp $KUBECONFIG ~/.kube/config

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file="k3d.tfvars" -out out.tfplan

      - name: Terraform Apply
        id: apply
        if: github.event_name == 'pull_request'
        run: terraform apply -input=false out.tfplan

      - name: Create Testkube Tests
        id: create_tests
        uses: kubeshop/testkube-docker-action@v1
        with:
          command: create
          resource: test
          namespace: testkube
          parameters: "--name curl-test --type curl/test --test-content-type git-file --git-uri https://github.com/Element84/swoop.git --git-branch hm/testkube --git-path tests/testkube/curltest.json"

      - name: Run Testkube Tests
        id: run_tests
        uses: kubeshop/testkube-docker-action@v1
        with:
          command: run
          resource: test
          parameters: "--watch curl-test"
